{% set name = "sagemaker" %}
{% set version = "2.198.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/sagemaker/sagemaker-{{ version }}.tar.gz
  sha256: 6798d51a32e583c6d29355d947423b53e0d10271ae36bce609c8dd5ddced3e7b

build:
  entry_points:
    - sagemaker-upgrade-v2=sagemaker.cli.compatibility.v2.sagemaker_upgrade_v2:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=23.1.0,<24
    - boto3 >=1.26.131,<2.0
    - cloudpickle ==2.2.1
    - google-pasta
    - numpy >=1.9.0,<2.0
    - protobuf >=3.1,<4.0
    - protobuf3-to-dict >=0.1.5,<1.0
    - smdebug-rulesconfig ==1.0.1
    - importlib-metadata >=1.4.0,<5.0
    - packaging >=20.0
    - pandas
    - pathos
    - schema
    - pyyaml ==6.0
    - jsonschema
    - platformdirs
    - tblib ==1.7.0

test:
  imports:
    - sagemaker
    - sagemaker.amazon
    - sagemaker.apiutils
    - sagemaker.automl
    - sagemaker.chainer
    - sagemaker.cli
    - sagemaker.cli.compatibility
    - sagemaker.cli.compatibility.v2
    - sagemaker.cli.compatibility.v2.modifiers
    - sagemaker.debugger
    - sagemaker.feature_store
    - sagemaker.lineage
    - sagemaker.local
    - sagemaker.model_monitor
    - sagemaker.mxnet
    - sagemaker.pytorch
    - sagemaker.rl
    - sagemaker.sklearn
    - sagemaker.spark
    - sagemaker.sparkml
    - sagemaker.tensorflow
    - sagemaker.workflow
    - sagemaker.xgboost
  commands:
    - pip check
    - sagemaker-upgrade-v2 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/sagemaker-python-sdk/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Open source library for training and deploying models on Amazon SageMaker.
  doc_url: https://sagemaker.readthedocs.io/en/stable/
  dev_url: https://github.com/aws/sagemaker-python-sdk/

extra:
  recipe-maintainers:
    - raybellwaves
